# Generated by Django 5.2.5 on 2025-08-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='imagens/')),
                ('traducao', models.TextField(blank=True, null=True)),
                ('boxes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
